# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=200)),
                ('ea', models.IntegerField()),
                ('img_src', models.ImageField(upload_to='')),
            ],
        ),
    ]
