# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='order_ea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='ea',
            field=models.IntegerField(default=0),
        ),
    ]
