# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190219_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
