# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190219_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=6)),
                ('order_phone', models.CharField(max_length=15)),
                ('order_addr1', models.TextField()),
                ('order_addr2', models.TextField()),
                ('order_email', models.CharField(max_length=30)),
                ('order_ea', models.IntegerField(default=1)),
                ('order_confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
