# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190219_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderperson',
            name='good_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Good'),
        ),
    ]
