# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_orderperson_good_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='order_ea',
        ),
    ]
