# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_good_order_ea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderperson',
            name='order_name',
        ),
    ]
