# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_orderperson_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDash',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ea', models.IntegerField()),
                ('total_order_ea', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
            options={
                'db_table': 'order_dash',
                'managed': False,
            },
        ),
    ]
