# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190219_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderperson',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
