# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_orderperson_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='img_src',
            field=models.ImageField(upload_to='blog/static/goodsImage'),
        ),
    ]
