# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_orderperson_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderperson',
            name='order_name',
            field=models.CharField(max_length=6),
        ),
    ]
