# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190220_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderperson',
            name='order_addr1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='orderperson',
            name='order_addr2',
            field=models.CharField(max_length=60),
        ),
    ]
